# Generated by Django 4.0.6 on 2022-08-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_messagesbackend_alter_customuser_api_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagesbackend',
            unique_together={('message', 'from_email')},
        ),
    ]
