# Generated by Django 3.2.9 on 2022-08-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('from_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Facts.category')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
