# Generated by Django 3.2.9 on 2022-08-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='from_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_facts', to='Facts.category'),
        ),
    ]
