# Generated by Django 3.2.9 on 2022-12-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facts', '0004_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='from_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_facts', to='Facts.category'),
        ),
    ]
